import img from '../../assets/1.jpg'

export const serviceList = [
    {text: 'Лазерная эпиляция',
     serviceUrl:'epilation',
     imgUrl:img},
    {text: 'Лазерная шлифовка',
     serviceUrl:'epilation',
     imgUrl: img
    },
    {text: 'Лазерное омоложение',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерная удаление пигментации',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерный пилинг',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерное удаление акне',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерное удаление сосудов',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерная эпиляция',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерная шлифовка',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерное омоложение',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерная удаление пигментации',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерный пилинг',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерное удаление акне',
        serviceUrl:'epilation',
        imgUrl:img},
    {text: 'Лазерное удаление сосудов',
        serviceUrl:'epilation',
        imgUrl:img},
];